In [158]:
from bs4 import BeautifulSoup
from splinter import Browser
from webdriver_manager.chrome import ChromeDriverManager
import pymongo
import numpy as np
import pandas as pd
import requests

In [2]:
# Splinter
executable_path = {'executable_path': ChromeDriverManager().install()}
browser = Browser('chrome', **executable_path, headless=False)

[WDM] - ====== WebDriver manager ======
INFO:WDM:====== WebDriver manager ======
[WDM] - Current google-chrome version is 103.0.5060
INFO:WDM:Current google-chrome version is 103.0.5060
[WDM] - Get LATEST chromedriver version for 103.0.5060 google-chrome
INFO:WDM:Get LATEST chromedriver version for 103.0.5060 google-chrome
[WDM] - About to download new driver from https://chromedriver.storage.googleapis.com/103.0.5060.53/chromedriver_mac64.zip
INFO:WDM:About to download new driver from https://chromedriver.storage.googleapis.com/103.0.5060.53/chromedriver_mac64.zip
[WDM] - Driver has been saved in cache [/Users/ap20/.wdm/drivers/chromedriver/mac64/103.0.5060.53]
INFO:WDM:Driver has been saved in cache [/Users/ap20/.wdm/drivers/chromedriver/mac64/103.0.5060.53]

In [26]:
# Batting stats URLs
batting_url_list = ['https://www.espn.com/mlb/stats/player/_/view/batting/season/2021/seasontype/2/table/batting/sort/homeRuns/dir/desc',
                    'https://www.espn.com/mlb/stats/player/_/view/batting/season/2020/seasontype/2/table/batting/sort/homeRuns/dir/desc',
                    'https://www.espn.com/mlb/stats/player/_/view/batting/season/2019/seasontype/2/table/batting/sort/homeRuns/dir/desc']

In [56]:
# $$$$$$$
# Function for scraping Abbreviation

def abbreviation(url):    
    browser.visit(url)

    html = browser.html
    soup = BeautifulSoup(html, 'html.parser')
    
    results = soup.find_all('tr', class_ = 'Table__TR Table__TR--sm Table__even')

    abrs = []

    for query in results:
        try:        
            abr = query.span.text    
            abrs.append(abr)
        
        except AttributeError as e:
            print(e)  
    
    return abrs

In [63]:
# $$$$$$
# Abbreviation column variables
abr_2021 = abbreviation(batting_url_list[0])
abr_2020 = abbreviation(batting_url_list[1])
abr_2019 = abbreviation(batting_url_list[2])

'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'

In [71]:
# $$$$$$
# Function for scraping Name

def name(url):
    browser.visit(url)

    html = browser.html
    soup = BeautifulSoup(html, 'html.parser')
    
    results = soup.find_all('tr', class_ = 'Table__TR Table__TR--sm Table__even')

    names = []

    for query in results:        

        try:        
            full_name = query.a.text    
            names.append(full_name)
        
        except AttributeError as e:
            print(e)  
    
    return names

In [81]:
# $$$$$
# Names variables, shows error but the variables are working
names_2021 = name(batting_url_list[0])
names_2020 = name(batting_url_list[1])

'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'

WebDriverException: Message: unknown error: unexpected command response
  (Session info: chrome=103.0.5060.114)
Stacktrace:
0   chromedriver                        0x00000001051bb079 chromedriver + 4444281
1   chromedriver                        0x0000000105147403 chromedriver + 3970051
2   chromedriver                        0x0000000104de2038 chromedriver + 409656
3   chromedriver                        0x0000000104dcf3c8 chromedriver + 332744
4   chromedriver                        0x0000000104dceac7 chromedriver + 330439
5   chromedriver                        0x0000000104dce047 chromedriver + 327751
6   chromedriver                        0x0000000104dcd803 chromedriver + 325635
7   chromedriver                        0x0000000104de91fa chromedriver + 438778
8   chromedriver                        0x0000000104e4862d chromedriver + 828973
9   chromedriver                        0x0000000104e35683 chromedriver + 751235
10  chromedriver                        0x0000000104e0ba45 chromedriver + 580165
11  chromedriver                        0x0000000104e0ca95 chromedriver + 584341
12  chromedriver                        0x000000010518c55d chromedriver + 4253021
13  chromedriver                        0x00000001051913a1 chromedriver + 4273057
14  chromedriver                        0x000000010519616f chromedriver + 4292975
15  chromedriver                        0x0000000105191dea chromedriver + 4275690
16  chromedriver                        0x000000010516b54f chromedriver + 4117839
17  chromedriver                        0x00000001051abed8 chromedriver + 4382424
18  chromedriver                        0x00000001051ac05f chromedriver + 4382815
19  chromedriver                        0x00000001051c28d5 chromedriver + 4475093
20  libsystem_pthread.dylib             0x00007ff8129874e1 _pthread_start + 125
21  libsystem_pthread.dylib             0x00007ff812982f6b thread_start + 15

In [80]:
# $$$$$$
# Name variable
names_2019 = name('https://www.espn.com/mlb/stats/player/_/view/batting/season/2019/seasontype/2/table/batting/sort/homeRuns/dir/desc')

'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'

In [96]:
# $$$$$$$$$$$
# Scrape for Name and ABREVIATION
# Ground work for above 2 functions

#url = 'https://www.espn.com/mlb/stats/player/_/view/batting/season/2021/seasontype/2/table/batting/sort/homeRuns/dir/desc'
#browser.visit(url)

#html = browser.html
#soup = BeautifulSoup(html, 'html.parser')

#result = soup.find_all('tr', class_ = 'Table__TR Table__TR--sm Table__even')

#names = []
#abrs = []

#for query in result:
#    try:
#        
#        full_name = query.a.text    
#        abr = query.span.text
#        print(full_name)
#        print(abr)
#        print('-----------')
    
#        names.append(full_name)
#        abrs.append(abr)
        
#    except AttributeError as e:
#       print(e)

In [91]:
# Function for scraping desired batting data
def batting(url):
    tables = pd.read_html(url)

    t1 = tables[0]
    t2 = tables[1]

    batting_df = t1.join(t2)

    clean_batting_df = batting_df.drop(['OBP','SLG','OPS','WAR'], axis= 1)

    clean_batting_df.rename(columns = {'Name':'Names','GP':'Games Played', 'AB':'At Bats','R': 'Runs', 'H':'Hits', 'HR':'Home Runs',
                                        'RBI':'Runs Batted In','TB':'Total Bases', 'BB':'Walks', 'K':'Strikeouts', 'SB':'Stolen Bases'}, inplace = True)

    return clean_batting_df

In [208]:
# $READY$

# 2021 Batting Table
batting_2021_df = batting(batting_url_list[0])

# Insert new columns
batting_2021_df.insert(1,'Name',names_2021)
batting_2021_df.insert(2,'Team',abr_2021)

# Drop Teams column
batting_2021_df.drop(['Names'], axis=1, inplace=True)

batting_2021_df.head()

batting_2021_df.to_csv('csvs/batting_2021.csv', index=False)

In [209]:
# $READY$

# 2020 Batting Table
batting_2020_df = batting(batting_url_list[1])

# Insert new columns
batting_2020_df.insert(1,'Name',names_2020)
batting_2020_df.insert(2,'Team',abr_2020)

# Drop Teams column
batting_2020_df.drop(['Names'], axis=1, inplace=True)

batting_2020_df.head()

batting_2020_df.to_csv('csvs/batting_2020.csv', index=False)

In [210]:
# $READY$

# 2019 Batting Table
batting_2019_df = batting(batting_url_list[2])

# Insert new columns
batting_2019_df.insert(1,'Name',names_2019)
batting_2019_df.insert(2,'Team',abr_2019)

# Drop Teams column
batting_2019_df.drop(['Names'], axis=1, inplace=True)

batting_2019_df.head()

batting_2019_df.to_csv('csvs/batting_2019.csv', index=False)

In [135]:
# Scraping Attendance stats
#
#
#
#
#

In [3]:
# Attendance URLs
attendance_url_list = ['https://www.espn.com/mlb/attendance/_/year/2021',
                        'https://www.espn.com/mlb/attendance/_/year/2019']

In [217]:
# $$$$$
# Function to return clean dataframes for attendance

def attendance(url):
    
    tables = pd.read_html(url)

    attendance_df = tables[0]

    # Rename columns
    attendance_df.rename(columns = {0 :'RK', 1 :'Teams', 2 :'Home Games', 3 :'Home Total', 4 :'Home Avg', 6 :'Road Games', 7 :'Road Avg',
                                    9 :'Overall Games', 10 :'Overall Avg'}, inplace = True)
    # Drop by Index
    attendance_df.drop([0,1], inplace=True)

    # Reset Index
    attendance_df.reset_index(inplace=True)

    # Drop by column
    attendance_df.drop(['index',5, 8, 11], axis=1, inplace=True)

    # Created list to replace Teams column
    team = ['Arizona Diamondbacks', 'Atlanta Braves','Baltimore Orioles','Boston Red Sox','Chicago Cubs','Chicago White Sox',
            'Cincinnati Reds','Cleveland Guardians','Colorado Rockies','Detroit Tigers','Houston Astros','Kansas City Royals',
                'Los Angeles Angels','Los Angeles Dodgers','Miami Marlins','Milwaukee Brewers','Minnesota Twins','New York Mets',
                    'New York Yankees','Oakland Athletics','Philadelphia Phillies','Pittsburgh Pirates','San Diego Padres','San Francisco Giants',
                        'Seattle Mariners','St. Louis Cardinals','Tampa Bay Rays','Texas Rangers','Toronto Blue Jays','Washington Nationals']
    abr = ['ARI','ATl','BAL','BOS','CHC','CWS','CIN','CLE','COL','DET','HOU','KC','LAA','LA','MIA','MIL','MIN','NYM','NYY','OAK','PHI','PIT','SD','SF',
            'SEA','STL','TB','TEX','TOR','WAS']

    # Place alphabetical
    attendance_df.sort_values(by=['Teams'], inplace=True)

    # Insert new columns
    attendance_df.insert(1,'Team',team)
    attendance_df.insert(2,'ABR',abr)

    # Drop Teams column
    attendance_df.drop(['Teams'], axis=1, inplace=True)

    # Convert column RK to INT
    complete_attendace_df = attendance_df.astype({"RK": int},  errors='raise') 

    # Resorts dataframe back to normal based on rank
    complete_attendace_df.sort_values(by=['RK'], inplace=True)

    # Convert necessary columns to INT
    complete_attendace_df[['Home Total', 'Home Avg','Road Avg','Overall Avg']] = complete_attendace_df[['Home Total', 'Home Avg','Road Avg','Overall Avg']].astype(int)

# Had to marker out the formatting due to conflict with exporting to csv
#
#    complete_attendace_df = complete_attendace_df.style.format({'Home Total':'{:,.0f}',
#                                                    'Home Avg':'{:,.0f}',
#                                                        'Road Avg':'{:,.0f}',
#                                                            'Overall Avg':'{:,.0f}'})

    return complete_attendace_df

In [219]:
# $READY$

# COMPLETE ATTENDANCE CHARTS
attendance_2021_df = attendance('https://www.espn.com/mlb/attendance/_/year/2021')
attendance_2019_df = attendance('https://www.espn.com/mlb/attendance/_/year/2019')

In [220]:
attendance_2021_df.to_csv('csvs/attendance_2021.csv', index=False)
attendance_2019_df.to_csv('csvs/attendance_2019.csv', index=False)

In [148]:
# $$$$$
# Ground work for attendace function above
# attendance URL list

tables = pd.read_html(url)

attendance_df = tables[0]

# Rename columns
attendance_df.rename(columns = {0 :'RK', 1 :'Teams', 2 :'Home Games', 3 :'Home Total', 4 :'Home Avg', 6 :'Road Games', 7 :'Road Avg',
                                    9 :'Overall Games', 10 :'Overall Avg'}, inplace = True)
# Drop by Index
attendance_df.drop([0,1], inplace=True)

# Reset Index
attendance_df.reset_index(inplace=True)

# Drop by column
attendance_df.drop(['index',5, 8, 11], axis=1, inplace=True)

# Created list to replace Teams column
team = ['Arizona Diamondbacks', 'Atlanta Braves','Baltimore Orioles','Boston Red Sox','Chicago Cubs','Chicago White Sox',
            'Cincinnati Reds','Cleveland Guardians','Colorado Rockies','Detroit Tigers','Houston Astros','Kansas City Royals',
                'Los Angeles Angels','Los Angeles Dodgers','Miami Marlins','Milwaukee Brewers','Minnesota Twins','New York Mets',
                    'New York Yankees','Oakland Athletics','Philadelphia Phillies','Pittsburgh Pirates','San Diego Padres','San Francisco Giants',
                        'Seattle Mariners','St. Louis Cardinals','Tampa Bay Rays','Texas Rangers','Toronto Blue Jays','Washington Nationals']
abr = ['ARI','ATl','BAL','BOS','CHC','CWS','CIN','CLE','COL','DET','HOU','KC','LAA','LA','MIA','MIL','MIN','NYM','NYY','OAK','PHI','PIT','SD','SF',
            'SEA','STL','TB','TEX','TOR','WAS']

# Place alphabetical
attendance_df.sort_values(by=['Teams'], inplace=True)

# Insert new columns
attendance_df.insert(1,'Team',team)
attendance_df.insert(2,'ABR',abr)

# Drop Teams column
attendance_df.drop(['Teams'], axis=1, inplace=True)

# Change column RK to INT
complete_attendace_df = attendance_df.astype({"RK": int},  errors='raise') 

# Resorts dataframe back to normal based on rank
complete_attendace_df.sort_values(by=['RK'], inplace=True)

In [106]:
browser.quit()

In [107]:
# Team Payroll
#
#
#
#
payroll_url = 'http://www.stevetheump.com/Payrolls.htm'

In [225]:
# Payroll DFs for each year

tables = pd.read_html(payroll_url)

payroll_2021_df = tables[2]
payroll_2020_df = tables[3]
payroll_2019_df = tables[4]

In [226]:
# $$$$$
# Payroll 2021 clean up

# Rename columns
payroll_2021_df.rename(columns = {0 :'RK', 1 :'Team', 2 :'Roster', 3 :'Active', 4 :'Injured Reserve'}, inplace = True)

# Drop by Index
payroll_2021_df.drop([0,17], inplace=True)

# Reset Index
payroll_2021_df.reset_index(inplace=True)

# Drop by column
payroll_2021_df.drop(['index',5, 6, 7], axis=1, inplace=True)

# Specified columns to change
cols = ['Active','Injured Reserve']

# Removed commas and $ signs from specified columns to convert to INT
payroll_2021_df[cols] = payroll_2021_df[cols].replace({'\$': '', ',': ''}, regex=True)

# Replacing the - in columns with NaN values then replacing NaN values to 0
payroll_2021_df = payroll_2021_df.replace('-',np.NaN)
payroll_2021_df = payroll_2021_df.fillna(0)

# Covert desired colums to INT tobe able to make 'Total' column
payroll_2021_df[['Active', 'Injured Reserve']] = payroll_2021_df[['Active', 'Injured Reserve']].astype(int)

# 'Active' + 'Injured Reserve' = 'Total'
payroll_2021_df['Total'] = payroll_2021_df['Active'] + payroll_2021_df['Injured Reserve']


# Format
#payroll_2021_df = payroll_2021_df.style.format({'Active':'${:,.0f}',
#                                                    'Injured Reserve':'${:,.0f}',
#                                                        'Total':'${:,.0f}'})

In [228]:
payroll_2021_df.to_csv('csvs/payroll_2021.csv', index=False)

In [229]:
# $$$$$
# Payroll 2020 clean up

# Rename columns
payroll_2020_df.rename(columns = {0 :'RK', 1 :'Team', 2 :'Roster', 3 :'Active', 4 :'Injured Reserve'}, inplace = True)

# Drop by Index
payroll_2020_df.drop([0,17], inplace=True)

# Reset Index
payroll_2020_df.reset_index(inplace=True)

# Drop by column
payroll_2020_df.drop(['index',5, 6], axis=1, inplace=True)

# Specified columns to change
cols = ['Active','Injured Reserve']

# Removed commas and $ signs from specified columns to convert to INT
payroll_2020_df[cols] = payroll_2020_df[cols].replace({'\$': '', ',': ''}, regex=True)

# Replacing the - in columns with NaN values then replacing NaN values to 0
payroll_2020_df = payroll_2020_df.replace('-',np.NaN)
payroll_2020_df = payroll_2020_df.fillna(0)

# Covert desired colums to INT tobe able to make 'Total' column
payroll_2020_df[['Active', 'Injured Reserve']] = payroll_2020_df[['Active', 'Injured Reserve']].astype(int)

# 'Active' + 'Injured Reserve' = 'Total'
payroll_2020_df['Total'] = payroll_2020_df['Active'] + payroll_2020_df['Injured Reserve']

# Format
#payroll_2020_df = payroll_2020_df.style.format({'Active':'${:,.0f}',
#                                                    'Injured Reserve':'${:,.0f}',
#                                                        'Total':'${:,.0f}'})
payroll_2020_df

    RK                   Team Roster    Active  Injured Reserve     Total
0    1       New York Yankees     30  69232242         20477779  89710021
1    2    Los Angeles Dodgers     30  63422960         16586419  80009379
2    3         Boston Red Sox     30  43391294         15667552  59058846
3    4         Houston Astros     30  78018436          2098704  80117140
4    5          New York Mets     30  51189151         15107798  66296949
5    6           Chicago Cubs     30  70481778          5185185  75666963
6    7  Philadelphia Phillies     30  62757909          4496852  67254761
7    8   San Francisco Giants     30  36264864         13535622  49800486
8    9    St. Louis Cardinals     30  62008777          1174075  63182852
9   10       San Diego Padres     30  55877388           838186  56715574
10  11     Los Angeles Angels     30  64960781          4321648  69282429
11  12   Washington Nationals     30  64174147           448741  64622888
12  13         Atlanta Braves     30  44928451         16347037  61275488
13  14   Arizona Diamondbacks     30  33233780           425852  33659632
14  15          Texas Rangers     30  53050371          1637037  54687408
15  16       Colorado Rockies     30  46182221           740741  46922962
16  17        Cincinnati Reds     30  51103024          2212963  53315987
17  18      Chicago White Sox     30  48136667          2059259  50195926
18  19      Toronto Blue Jays     30  32443239          4335555  36778794
19  20        Minnesota Twins     30  39136050          6804074  45940124
20  21       Seattle Mariners     30  26669482          2132667  28802149
21  22         Detroit Tigers     30  26713447         10356481  37069928
22  23      Milwaukee Brewers     30  36898572          2506704  39405276
23  24      Cleveland Indians     30  36239337           694444  36933781
24  25     Kansas City Royals     30  32316226          2093083  34409309
25  26      Oakland Athletics     30  35311894           208704  35520598
26  27         Tampa Bay Rays     30  25888333           424926  26313259
27  28          Miami Marlins     30  17356374          1204445  18560819
28  29     Pittsburgh Pirates     30  12013521          9757407  21770928
29  30      Baltimore Orioles     30  21524874          2393703  23918577

In [230]:
payroll_2020_df.to_csv('csvs/payroll_2020.csv', index=False)

In [231]:
# $$$$$
# Payroll 2019 clean up

# Rename columns
payroll_2019_df.rename(columns = {0 :'RK', 1 :'Team', 2 :'Roster', 3 :'Active', 4 :'Injured Reserve'}, inplace = True)

# Drop by Index
payroll_2019_df.drop([0,14], inplace=True)

# Reset Index
payroll_2019_df.reset_index(inplace=True)

# Drop by column
payroll_2019_df.drop(['index'], axis=1, inplace=True)

# Specified columns to change
cols = ['Active','Injured Reserve']

# Removed commas and $ signs from specified columns to convert to INT
payroll_2019_df[cols] = payroll_2019_df[cols].replace({'\$': '', ',': ''}, regex=True)

# Replacing the - in columns with NaN values then replacing NaN values to 0
payroll_2019_df = payroll_2019_df.replace('-',np.NaN)
payroll_2019_df = payroll_2019_df.fillna(0)

# Covert desired colums to INT tobe able to make 'Total' column
payroll_2019_df[['Active', 'Injured Reserve']] = payroll_2019_df[['Active', 'Injured Reserve']].astype(int)

# 'Active' + 'Injured Reserve' = 'Total'
payroll_2019_df['Total'] = payroll_2019_df['Active'] + payroll_2019_df['Injured Reserve']

# Format
#payroll_2019_df = payroll_2019_df.style.format({'Active':'${:,.0f}',
#                                                    'Injured Reserve':'${:,.0f}',
#                                                        'Total':'${:,.0f}'})
payroll_2019_df

    RK                   Team Roster     Active  Injured Reserve      Total
0    1         Boston Red Sox     25  187232500         15689000  202921500
1    2           Chicago Cubs     25  194081714         11475000  205556714
2    3       New York Yankees     25  118832077         87252771  206084848
3    4    Los Angeles Dodgers     25   99803334         52316668  152120002
4    5   San Francisco Giants     25  157271237         21000000  178271237
5    6    St. Louis Cardinals     25  125365166         33005100  158370266
6    7   Washington Nationals     25  154176081          7539300  161715381
7    8         Houston Astros     25  147619666         12100000  159719666
8    9     Los Angeles Angels     25  132175083         26703500  158878583
9   10          New York Mets     25   91576770         50572500  142149270
10  11       Seattle Mariners     25  116382175         22482900  138865075
11  12       Colorado Rockies     25  125185509         20747500  145933009
12  13  Philadelphia Phillies     25  131152962          9559000  140711962
13  14          Texas Rangers     25  104349564          1668000  106017564
14  15        Cincinnati Reds     25  106440714         19982500  126423214
15  16      Milwaukee Brewers     25  108403700         13126700  121530400
16  17   Arizona Diamondbacks     25   96777231         11124600  107901831
17  18        Minnesota Twins     25  101056933         12270000  113326933
18  19      Cleveland Indians     25   88713833         30277868  118991701
19  20         Detroit Tigers     25   97988900          3934500  101923400
20  21         Atlanta Braves     25   89551043         23825000  113376043
21  22      Toronto Blue Jays     25   54568171          8603000   63171171
22  23     Kansas City Royals     25   67941887         28605350   96547237
23  24       San Diego Padres     25   63068635         10965200   74033835
24  25      Oakland Athletics     25   84345833          6972500   91318333
25  26      Chicago White Sox     25   83757121          4555000   88312121
26  27     Pittsburgh Pirates     25   54577502         20230500   74808002
27  28      Baltimore Orioles     25   61124882         11558000   72682882
28  29          Miami Marlins     25   69574714          1665000   71239714
29  30         Tampa Bay Rays     25   49084731          4360200   53444931

In [232]:
payroll_2019_df.to_csv('csvs/payroll_2019.csv', index=False)