In [2]:
from bs4 import BeautifulSoup
from splinter import Browser
from webdriver_manager.chrome import ChromeDriverManager
import pymongo
import pandas as pd
import requests

In [98]:
# Splinter
executable_path = {'executable_path': ChromeDriverManager().install()}
browser = Browser('chrome', **executable_path, headless=False)

[WDM] - ====== WebDriver manager ======
INFO:WDM:====== WebDriver manager ======
[WDM] - Current google-chrome version is 103.0.5060
INFO:WDM:Current google-chrome version is 103.0.5060
[WDM] - Get LATEST chromedriver version for 103.0.5060 google-chrome
INFO:WDM:Get LATEST chromedriver version for 103.0.5060 google-chrome
[WDM] - Driver [/Users/ap20/.wdm/drivers/chromedriver/mac64/103.0.5060.53/chromedriver] found in cache
INFO:WDM:Driver [/Users/ap20/.wdm/drivers/chromedriver/mac64/103.0.5060.53/chromedriver] found in cache

In [47]:
# Function for scraping Names and ABR
# Scraping Batting stats 1 of 3
url = 'https://www.espn.com/mlb/stats/player/_/view/batting/season/2021/seasontype/2/table/batting/sort/homeRuns/dir/desc'
browser.visit(url)

def name(url):
    browser.visit(url)

    html = requests.get(url)
    soup = BeautifulSoup(html.text, 'html.parser')
    
    results = soup.find_all('tr', class_ = 'Table__TR Table__TR--sm Table__even')

    names = []
    abrs = []

    for query in result:

        name = query.a.text
        abr = query.span.text

        names.append(name)
        abrs.append(abr)
    
    return[name, abr]

None

In [105]:
# Scrape for Name and ABREVIATION

url = 'https://www.espn.com/mlb/stats/player/_/view/batting/season/2021/seasontype/2/table/batting/sort/homeRuns/dir/desc'
browser.visit(url)

html = browser.html
soup = BeautifulSoup(html, 'html.parser')

result = soup.find_all('tr', class_ = 'Table__TR Table__TR--sm Table__even')

names = []
abrs = []

for query in result:    

    full_name = query.a    
    #abr = query.span.text
    print(full_name)
    print('________')
    
    names.append(full_name)
    #abrs.append(abr.text)

<a class="AnchorLink" data-player-uid="s:1~l:10~a:31127" href="https://www.espn.com/mlb/player/_/id/31127" tabindex="0">Salvador Perez</a>
________
<a class="AnchorLink" data-player-uid="s:1~l:10~a:35002" href="https://www.espn.com/mlb/player/_/id/35002" tabindex="0">Vladimir Guerrero Jr.</a>
________
<a class="AnchorLink" data-player-uid="s:1~l:10~a:39832" href="https://www.espn.com/mlb/player/_/id/39832" tabindex="0">Shohei Ohtani</a>
________
<a class="AnchorLink" data-player-uid="s:1~l:10~a:32146" href="https://www.espn.com/mlb/player/_/id/32146" tabindex="0">Marcus Semien</a>
________
<a class="AnchorLink" data-player-uid="s:1~l:10~a:35983" href="https://www.espn.com/mlb/player/_/id/35983" tabindex="0">Fernando Tatis Jr.</a>
________
<a class="AnchorLink" data-player-uid="s:1~l:10~a:32767" href="https://www.espn.com/mlb/player/_/id/32767" tabindex="0">Matt Olson</a>
________
<a class="AnchorLink" data-player-uid="s:1~l:10~a:32771" href="https://www.espn.com/mlb/player/_/id/32771" tabindex="0">Mitch Haniger</a>
________
<a class="AnchorLink" data-player-uid="s:1~l:10~a:33192" href="https://www.espn.com/mlb/player/_/id/33192" tabindex="0">Aaron Judge</a>
________
<a class="AnchorLink" data-player-uid="s:1~l:10~a:39961" href="https://www.espn.com/mlb/player/_/id/39961" tabindex="0">Brandon Lowe</a>
________
<a class="AnchorLink" data-player-uid="s:1~l:10~a:32664" href="https://www.espn.com/mlb/player/_/id/32664" tabindex="0">Adam Duvall</a>
________
<a class="AnchorLink" data-player-uid="s:1~l:10~a:32818" href="https://www.espn.com/mlb/player/_/id/32818" tabindex="0">Joey Gallo</a>
________
<a class="AnchorLink" data-player-uid="s:1~l:10~a:33859" href="https://www.espn.com/mlb/player/_/id/33859" tabindex="0">Rafael Devers</a>
________
<a class="AnchorLink" data-player-uid="s:1~l:10~a:37498" href="https://www.espn.com/mlb/player/_/id/37498" tabindex="0">Pete Alonso</a>
________
<a class="AnchorLink" data-player-uid="s:1~l:10~a:28670" href="https://www.espn.com/mlb/player/_/id/28670" tabindex="0">Joey Votto</a>
________
<a class="AnchorLink" data-player-uid="s:1~l:10~a:32801" href="https://www.espn.com/mlb/player/_/id/32801" tabindex="0">Jose Ramirez</a>
________
<a class="AnchorLink" data-player-uid="s:1~l:10~a:33303" href="https://www.espn.com/mlb/player/_/id/33303" tabindex="0">Max Muncy</a>
________
<a class="AnchorLink" data-player-uid="s:1~l:10~a:30583" href="https://www.espn.com/mlb/player/_/id/30583" tabindex="0">Giancarlo Stanton</a>
________
<a class="AnchorLink" data-player-uid="s:1~l:10~a:30819" href="https://www.espn.com/mlb/player/_/id/30819" tabindex="0">Kyle Seager</a>
________
<a class="AnchorLink" data-player-uid="s:1~l:10~a:30951" href="https://www.espn.com/mlb/player/_/id/30951" tabindex="0">Bryce Harper</a>
________
<a class="AnchorLink" data-player-uid="s:1~l:10~a:31187" href="https://www.espn.com/mlb/player/_/id/31187" tabindex="0">Nick Castellanos</a>
________
<a class="AnchorLink" data-player-uid="s:1~l:10~a:31261" href="https://www.espn.com/mlb/player/_/id/31261" tabindex="0">Nolan Arenado</a>
________
<a class="AnchorLink" data-player-uid="s:1~l:10~a:34168" href="https://www.espn.com/mlb/player/_/id/34168" tabindex="0">Tyler O'Neill</a>
________
<a class="AnchorLink" data-player-uid="s:1~l:10~a:32525" href="https://www.espn.com/mlb/player/_/id/32525" tabindex="0">Jorge Polanco</a>
________
<a class="AnchorLink" data-player-uid="s:1~l:10~a:32657" href="https://www.espn.com/mlb/player/_/id/32657" tabindex="0">Mike Zunino</a>
________
<a class="AnchorLink" data-player-uid="s:1~l:10~a:34940" href="https://www.espn.com/mlb/player/_/id/34940" tabindex="0">Ryan Mountcastle</a>
________
<a class="AnchorLink" data-player-uid="s:1~l:10~a:34982" href="https://www.espn.com/mlb/player/_/id/34982" tabindex="0">Austin Riley</a>
________
<a class="AnchorLink" data-player-uid="s:1~l:10~a:36018" href="https://www.espn.com/mlb/player/_/id/36018" tabindex="0">Yordan Alvarez</a>
________
<a class="AnchorLink" data-player-uid="s:1~l:10~a:6242" href="https://www.espn.com/mlb/player/_/id/6242" tabindex="0">Nelson Cruz</a>
________
<a class="AnchorLink" data-player-uid="s:1~l:10~a:33377" href="https://www.espn.com/mlb/player/_/id/33377" tabindex="0">Teoscar Hernandez</a>
________
<a class="AnchorLink" data-player-uid="s:1~l:10~a:33712" href="https://www.espn.com/mlb/player/_/id/33712" tabindex="0">Kyle Schwarber</a>
________
<a class="AnchorLink" data-player-uid="s:1~l:10~a:30193" href="https://www.espn.com/mlb/player/_/id/30193" tabindex="0">Freddie Freeman</a>
________
<a class="AnchorLink" data-player-uid="s:1~l:10~a:31027" href="https://www.espn.com/mlb/player/_/id/31027" tabindex="0">Paul Goldschmidt</a>
________
<a class="AnchorLink" data-player-uid="s:1~l:10~a:31662" href="https://www.espn.com/mlb/player/_/id/31662" tabindex="0">Jose Altuve</a>
________
<a class="AnchorLink" data-player-uid="s:1~l:10~a:32127" href="https://www.espn.com/mlb/player/_/id/32127" tabindex="0">Javier Baez</a>
________
<a class="AnchorLink" data-player-uid="s:1~l:10~a:32367" href="https://www.espn.com/mlb/player/_/id/32367" tabindex="0">Eugenio Suarez</a>
________
<a class="AnchorLink" data-player-uid="s:1~l:10~a:33205" href="https://www.espn.com/mlb/player/_/id/33205" tabindex="0">Hunter Renfroe</a>
________
<a class="AnchorLink" data-player-uid="s:1~l:10~a:35537" href="https://www.espn.com/mlb/player/_/id/35537" tabindex="0">Adolis Garcia</a>
________
<a class="AnchorLink" data-player-uid="s:1~l:10~a:31260" href="https://www.espn.com/mlb/player/_/id/31260" tabindex="0">Miguel Sano</a>
________
<a class="AnchorLink" data-player-uid="s:1~l:10~a:33095" href="https://www.espn.com/mlb/player/_/id/33095" tabindex="0">Jose Abreu</a>
________
<a class="AnchorLink" data-player-uid="s:1~l:10~a:33339" href="https://www.espn.com/mlb/player/_/id/33339" tabindex="0">Franmil Reyes</a>
________
<a class="AnchorLink" data-player-uid="s:1~l:10~a:33783" href="https://www.espn.com/mlb/player/_/id/33783" tabindex="0">Ozzie Albies</a>
________
<a class="AnchorLink" data-player-uid="s:1~l:10~a:34967" href="https://www.espn.com/mlb/player/_/id/34967" tabindex="0">Kyle Tucker</a>
________
<a class="AnchorLink" data-player-uid="s:1~l:10~a:35578" href="https://www.espn.com/mlb/player/_/id/35578" tabindex="0">Cedric Mullins</a>
________
<a class="AnchorLink" data-player-uid="s:1~l:10~a:30729" href="https://www.espn.com/mlb/player/_/id/30729" tabindex="0">Avisail Garcia</a>
________
<a class="AnchorLink" data-player-uid="s:1~l:10~a:30901" href="https://www.espn.com/mlb/player/_/id/30901" tabindex="0">Brandon Belt</a>
________
<a class="AnchorLink" data-player-uid="s:1~l:10~a:35673" href="https://www.espn.com/mlb/player/_/id/35673" tabindex="0">Jared Walsh</a>
________
<a class="AnchorLink" data-player-uid="s:1~l:10~a:36969" href="https://www.espn.com/mlb/player/_/id/36969" tabindex="0">Juan Soto</a>
________
<a class="AnchorLink" data-player-uid="s:1~l:10~a:38904" href="https://www.espn.com/mlb/player/_/id/38904" tabindex="0">Bo Bichette</a>
________
<a class="AnchorLink" data-player-uid="s:1~l:10~a:30272" href="https://www.espn.com/mlb/player/_/id/30272" tabindex="0">Eduardo Escobar</a>
________
<a class="AnchorLink" data-player-uid="s:1~l:10~a:31065" href="https://www.espn.com/mlb/player/_/id/31065" tabindex="0">J.D. Martinez</a>
________
None
________
None
________
None
________
None
________
None
________
None
________
None
________
None
________
None
________
None
________
None
________
None
________
None
________
None
________
None
________
None
________
None
________
None
________
None
________
None
________
None
________
None
________
None
________
None
________
None
________
None
________
None
________
None
________
None
________
None
________
None
________
None
________
None
________
None
________
None
________
None
________
None
________
None
________
None
________
None
________
None
________
None
________
None
________
None
________
None
________
None
________
None
________
None
________
None
________
None
________

In [85]:
result[0]

<tr class="Table__TR Table__TR--sm Table__even" data-idx="0"><td class="Table__TD">1</td><td class="Table__TD"><div class=""><a class="AnchorLink" data-player-uid="s:1~l:10~a:31127" href="https://www.espn.com/mlb/player/_/id/31127" tabindex="0">Salvador Perez</a><span class="pl2 n10 athleteCell__teamAbbrev">KC</span></div></td></tr>

In [ ]:
# Function for scraping batting desired batting data
def batting(url):
    tables = pd.read_html(url)

    t1 = tables[0]
    t2 = tables[1]

    batting_df = t1.join(t2)

    clean_batting_df = batting_df.drop(['OBP','SLG','OPS','WAR'], axis= 1)

    clean_batting_df.rename(columns = {'GP':'Games Played', 'AB':'At Bats','R': 'Runs', 'H':'Hits', 'HR':'Home Runs',
                                        'RBI':'Runs Batted In','TB':'Total Bases', 'BB':'Walks', 'K':'Strikeouts', 'SB':'Stolen Bases'}, inplace = True)

In [27]:
# Batting tables
tables = pd.read_html(url)

t1 = tables[0]
t2 = tables[1]

# Join dfs
batting_df = t1.join(t2)

# Drop columns
clean_batting_df = batting_df.drop(['OBP','SLG','OPS','WAR'], axis= 1)

# Rename columns
clean_batting_df.rename(columns = {'GP':'Games Played', 'AB':'At Bats','R': 'Runs', 'H':'Hits', 'HR':'Home Runs',
                                        'RBI':'Runs Batted In','TB':'Total Bases', 'BB':'Walks', 'K':'Strikeouts', 'SB':'Stolen Bases'}, inplace = True)

In [28]:
clean_batting_df

,RK,Name,POS,Games Played,At Bats,Runs,Hits,AVG,2B,3B,Home Runs,Runs Batted In,Total Bases,Walks,Strikeouts,Stolen Bases
0,1,Salvador PerezKC,C,161,620,88,169,0.273,24,0,48,121,337,28,170,1
1,1,Vladimir Guerrero Jr.TOR,1B,161,604,123,188,0.311,29,1,48,111,363,86,110,4
2,3,Shohei OhtaniLAA,SP,155,537,103,138,0.257,26,8,46,100,318,96,189,26
3,4,Marcus SemienTOR,2B,162,652,115,173,0.265,39,2,45,102,351,66,146,15
4,5,Fernando Tatis Jr.SD,SS,130,478,99,135,0.282,31,0,42,97,292,62,153,25
5,6,Matt OlsonOAK,1B,156,565,101,153,0.271,35,0,39,111,305,88,113,4
6,6,Mitch HanigerSEA,RF,157,620,110,157,0.253,23,2,39,100,301,54,169,1
7,6,Aaron JudgeNYY,CF,148,550,89,158,0.287,24,0,39,98,299,75,158,6
8,6,Brandon LoweTB,2B,149,535,97,132,0.247,31,0,39,99,280,68,167,7
9,10,Adam DuvallATL/MIA,CF,146,513,67,117,0.228,17,2,38,113,252,35,174,5
10,10,Joey GalloTEX/NYY,RF,154,498,90,99,0.199,13,1,38,77,228,111,213,6
11,10,Rafael DeversBOS,3B,156,591,101,165,0.279,37,1,38,113,318,62,143,5
12,13,Pete AlonsoNYM,1B,152,561,81,147,0.262,27,3,37,94,291,60,127,3
13,14,Joey VottoCIN,1B,129,448,73,119,0.266,23,1,36,99,252,77,127,1
14,14,Jose RamirezCLE,3B,152,552,111,147,0.266,32,5,36,103,297,72,87,27
15,14,Max MuncyLAD,3B,144,497,95,124,0.249,26,2,36,94,262,83,120,2
16,17,Giancarlo StantonNYY,DH,140,510,64,139,0.273,19,0,35,97,263,63,157,0
17,17,Kyle SeagerSEA,3B,159,603,73,128,0.212,29,1,35,101,264,59,161,3
18,17,Bryce HarperPHI,DH,141,488,101,151,0.309,42,1,35,84,300,100,134,13
19,20,Nick CastellanosCIN,RF,138,531,95,164,0.309,38,1,34,100,306,41,121,3
20,20,Nolan ArenadoSTL,3B,157,593,81,151,0.255,34,3,34,105,293,50,96,2
21,20,Tyler O'NeillSTL,LF,141,482,89,138,0.286,26,2,34,80,270,38,168,15
22,23,Jorge PolancoMIN,2B,152,588,97,158,0.269,35,2,33,98,296,45,118,11
23,23,Mike ZuninoTB,C,109,333,64,72,0.216,11,2,33,62,186,34,132,0
24,23,Ryan MountcastleBAL,1B,144,534,77,136,0.255,23,1,33,89,260,41,161,4
25,23,Austin RileyATL,3B,160,590,91,179,0.303,33,1,33,107,313,52,168,0
26,23,Yordan AlvarezHOU,LF,144,537,92,149,0.277,35,1,33,104,285,50,145,1
27,28,Nelson CruzMIN/TB,DH,146,513,79,136,0.265,21,1,32,86,255,51,126,3
28,28,Teoscar HernandezTOR,RF,143,550,92,163,0.296,29,0,32,116,288,36,148,12
29,28,Kyle SchwarberBOS/WSH,LF,113,399,76,106,0.266,19,0,32,71,221,64,127,1
30,31,Freddie FreemanATL,1B,159,600,120,180,0.300,25,2,31,83,302,85,107,8
31,31,Paul GoldschmidtSTL,1B,158,603,102,177,0.294,36,2,31,99,310,67,136,12
32,31,Jose AltuveHOU,2B,146,602,117,167,0.277,32,1,31,83,294,66,91,5
33,31,Javier BaezCHC/NYM,SS,142,502,80,133,0.265,18,2,31,87,248,28,184,18
34,31,Eugenio SuarezCIN,3B,145,505,71,100,0.198,23,0,31,79,216,56,171,0
35,31,Hunter RenfroeBOS,RF,144,521,89,135,0.259,33,0,31,96,261,44,130,1
36,31,Adolis GarciaTEX,RF,149,581,77,141,0.243,26,2,31,90,264,32,194,16
37,38,Miguel SanoMIN,1B,135,470,68,105,0.223,24,0,30,75,219,59,183,2
38,38,Jose AbreuCHW,1B,152,566,86,148,0.261,30,2,30,117,272,61,143,1
39,38,Franmil ReyesCLE,DH,115,418,57,106,0.254,18,2,30,85,218,43,149,4
40,38,Ozzie AlbiesATL,2B,156,629,103,163,0.259,40,7,30,106,307,47,128,20
41,38,Kyle TuckerHOU,RF,140,506,83,149,0.294,37,3,30,92,282,53,90,14
42,38,Cedric MullinsBAL,CF,159,602,91,175,0.291,37,5,30,59,312,59,125,30
43,44,Avisail GarciaMIL,RF,135,461,68,121,0.262,18,0,29,86,226,38,121,8
44,44,Brandon BeltSF,1B,97,325,65,89,0.274,14,2,29,59,194,48,103,3
45,44,Jared WalshLAA,1B,144,530,70,147,0.277,34,1,29,98,270,48,152,2
46,44,Juan SotoWSH,RF,151,502,111,157,0.313,20,2,29,95,268,145,93,9
47,44,Bo BichetteTOR,SS,159,640,121,191,0.298,30,1,29,102,310,40,137,25
48,49,Eduardo EscobarARI/MIL,3B,146,549,77,139,0.253,26,5,28,90,259,48,124,1
49,49,J.D. MartinezBOS,DH,148,570,92,163,0.286,42,3,28,99,295,55,150,0

In [135]:
# Scraping Attendance stats
#
#
#
#
#

In [3]:
url_list = ['https://www.espn.com/mlb/attendance/_/year/2021','https://www.espn.com/mlb/attendance/_/year/2019']

In [13]:
# $$$$$
# Function to return clean dataframes for attendance

def attendance(url):
    
    tables = pd.read_html(url)

    attendance_df = tables[0]

# Rename columns
    attendance_df.rename(columns = {0 :'RK', 1 :'Teams', 2 :'Home Games', 3 :'Home Total', 4 :'Home Avg', 6 :'Road Games', 7 :'Road Avg',
                                    9 :'Overall Games', 10 :'Overall Avg'}, inplace = True)
# Drop by Index
    attendance_df.drop([0,1], inplace=True)

# Reset Index
    attendance_df.reset_index(inplace=True)

# Drop by column
    attendance_df.drop(['index',5, 8, 11], axis=1, inplace=True)

# Created list to replace Teams column
    team = ['Arizona Diamondbacks', 'Atlanta Braves','Baltimore Orioles','Boston Red Sox','Chicago Cubs','Chicago White Sox',
            'Cincinnati Reds','Cleveland Guardians','Colorado Rockies','Detroit Tigers','Houston Astros','Kansas City Royals',
                'Los Angeles Angels','Los Angeles Dodgers','Miami Marlins','Milwaukee Brewers','Minnesota Twins','New York Mets',
                    'New York Yankees','Oakland Athletics','Philadelphia Phillies','Pittsburgh Pirates','San Diego Padres','San Francisco Giants',
                        'Seattle Mariners','St. Louis Cardinals','Tampa Bay Rays','Texas Rangers','Toronto Blue Jays','Washington Nationals']
    abr = ['ARI','ATl','BAL','BOS','CHC','CWS','CIN','CLE','COL','DET','HOU','KC','LAA','LA','MIA','MIL','MIN','NYM','NYY','OAK','PHI','PIT','SD','SF',
            'SEA','STL','TB','TEX','TOR','WAS']

# Place alphabetical
    attendance_df.sort_values(by=['Teams'], inplace=True)

# Insert new columns
    attendance_df.insert(1,'Team',team)
    attendance_df.insert(2,'ABR',abr)

# Drop Teams column
    attendance_df.drop(['Teams'], axis=1, inplace=True)

# Change column RK to INT
    complete_attendace_df = attendance_df.astype({"RK": int},  errors='raise') 

# Resorts dataframe back to normal based on rank
    complete_attendace_df.sort_values(by=['RK'], inplace=True)

    return complete_attendace_df

In [16]:
# COMPLETE ATTENDANCE CHARTS
attendance_2021 = attendance('https://www.espn.com/mlb/attendance/_/year/2021')
attendance_2019 = attendance('https://www.espn.com/mlb/attendance/_/year/2019')
attendance_2021

,RK,Team,ABR,Home Games,Home Total,Home Avg,Road Games,Road Avg,Overall Games,Overall Avg
0,1,Los Angeles Dodgers,LA,81,2804693,34625,81,25163,162,29894
1,2,Atlanta Braves,ATl,78,2300247,29490,78,17968,156,23729
2,3,San Diego Padres,SD,81,2191950,27061,79,22140,160,24631
3,4,St. Louis Cardinals,STL,80,2102530,26281,81,20518,161,23382
4,5,Texas Rangers,TEX,81,2110258,26052,80,14444,161,20284
5,6,Houston Astros,HOU,81,2068509,25537,81,17947,162,21742
6,7,Colorado Rockies,COL,78,1938645,24854,79,20252,157,22539
7,8,New York Yankees,NYY,80,1959854,24498,81,20612,161,22543
8,9,Chicago Cubs,CHC,81,1978934,24431,81,22637,162,23534
9,10,Milwaukee Brewers,MIL,81,1824282,22522,81,19548,162,21035
10,11,Boston Red Sox,BOS,81,1725323,21300,80,19693,161,20501
11,12,San Francisco Giants,SF,81,1679484,20734,80,22467,161,21595
12,13,New York Mets,NYM,72,1484665,20620,79,20723,151,20674
13,14,Chicago White Sox,CWS,78,1596385,20466,80,16576,158,18496
14,15,Philadelphia Phillies,PHI,79,1515890,19188,79,19985,158,19587
15,16,Los Angeles Angels,LAA,81,1512033,18667,81,19075,162,18871
16,17,Cincinnati Reds,CIN,81,1505024,18580,81,19527,162,19054
17,18,Washington Nationals,WAS,80,1465543,18319,78,17401,158,17866
18,19,Minnesota Twins,MIN,80,1310199,16377,79,17219,159,16795
19,20,Seattle Mariners,SEA,81,1215985,15012,79,16869,160,15929
20,21,Cleveland Guardians,CLE,77,1114368,14472,80,16264,157,15385
21,22,Kansas City Royals,KC,81,1159613,14316,80,16222,161,15263
22,23,Detroit Tigers,DET,81,1102623,13612,79,16359,160,14968
23,24,Arizona Diamondbacks,ARI,81,1043010,12876,80,20081,161,16456
24,25,Pittsburgh Pirates,PIT,81,859498,10611,80,20719,161,15633
25,26,Baltimore Orioles,BAL,78,793229,10169,80,16390,158,13319
26,27,Toronto Blue Jays,TOR,80,809557,10119,78,16398,158,13219
27,28,Tampa Bay Rays,TB,80,761072,9513,81,16339,161,12947
28,29,Oakland Athletics,OAK,80,701430,8767,81,19085,161,13958
29,30,Miami Marlins,MIA,81,642617,7933,79,18015,160,12911

In [148]:
tables = pd.read_html(url)

attendance_df = tables[0]

# Rename columns
attendance_df.rename(columns = {0 :'RK', 1 :'Teams', 2 :'Home Games', 3 :'Home Total', 4 :'Home Avg', 6 :'Road Games', 7 :'Road Avg',
                                    9 :'Overall Games', 10 :'Overall Avg'}, inplace = True)
# Drop by Index
attendance_df.drop([0,1], inplace=True)

# Reset Index
attendance_df.reset_index(inplace=True)

# Drop by column
attendance_df.drop(['index',5, 8, 11], axis=1, inplace=True)

# Created list to replace Teams column
team = ['Arizona Diamondbacks', 'Atlanta Braves','Baltimore Orioles','Boston Red Sox','Chicago Cubs','Chicago White Sox',
            'Cincinnati Reds','Cleveland Guardians','Colorado Rockies','Detroit Tigers','Houston Astros','Kansas City Royals',
                'Los Angeles Angels','Los Angeles Dodgers','Miami Marlins','Milwaukee Brewers','Minnesota Twins','New York Mets',
                    'New York Yankees','Oakland Athletics','Philadelphia Phillies','Pittsburgh Pirates','San Diego Padres','San Francisco Giants',
                        'Seattle Mariners','St. Louis Cardinals','Tampa Bay Rays','Texas Rangers','Toronto Blue Jays','Washington Nationals']
abr = ['ARI','ATl','BAL','BOS','CHC','CWS','CIN','CLE','COL','DET','HOU','KC','LAA','LA','MIA','MIL','MIN','NYM','NYY','OAK','PHI','PIT','SD','SF',
            'SEA','STL','TB','TEX','TOR','WAS']

# Place alphabetical
attendance_df.sort_values(by=['Teams'], inplace=True)

# Insert new columns
attendance_df.insert(1,'Team',team)
attendance_df.insert(2,'ABR',abr)

# Drop Teams column
attendance_df.drop(['Teams'], axis=1, inplace=True)

# Change column RK to INT
complete_attendace_df = attendance_df.astype({"RK": int},  errors='raise') 

# Resorts dataframe back to normal based on rank
complete_attendace_df.sort_values(by=['RK'], inplace=True)

In [150]:
complete_attendace_df.sort_values(by=['RK'], inplace=True)
complete_attendace_df

,RK,Team,ABR,Home Games,Home Total,Home Avg,Road Games,Road Avg,Overall Games,Overall Avg
0,1,Los Angeles Dodgers,LA,81,2804693,34625,81,25163,162,29894
1,2,Atlanta Braves,ATl,78,2300247,29490,78,17968,156,23729
2,3,San Diego Padres,SD,81,2191950,27061,79,22140,160,24631
3,4,St. Louis Cardinals,STL,80,2102530,26281,81,20518,161,23382
4,5,Texas Rangers,TEX,81,2110258,26052,80,14444,161,20284
5,6,Houston Astros,HOU,81,2068509,25537,81,17947,162,21742
6,7,Colorado Rockies,COL,78,1938645,24854,79,20252,157,22539
7,8,New York Yankees,NYY,80,1959854,24498,81,20612,161,22543
8,9,Chicago Cubs,CHC,81,1978934,24431,81,22637,162,23534
9,10,Milwaukee Brewers,MIL,81,1824282,22522,81,19548,162,21035
10,11,Boston Red Sox,BOS,81,1725323,21300,80,19693,161,20501
11,12,San Francisco Giants,SF,81,1679484,20734,80,22467,161,21595
12,13,New York Mets,NYM,72,1484665,20620,79,20723,151,20674
13,14,Chicago White Sox,CWS,78,1596385,20466,80,16576,158,18496
14,15,Philadelphia Phillies,PHI,79,1515890,19188,79,19985,158,19587
15,16,Los Angeles Angels,LAA,81,1512033,18667,81,19075,162,18871
16,17,Cincinnati Reds,CIN,81,1505024,18580,81,19527,162,19054
17,18,Washington Nationals,WAS,80,1465543,18319,78,17401,158,17866
18,19,Minnesota Twins,MIN,80,1310199,16377,79,17219,159,16795
19,20,Seattle Mariners,SEA,81,1215985,15012,79,16869,160,15929
20,21,Cleveland Guardians,CLE,77,1114368,14472,80,16264,157,15385
21,22,Kansas City Royals,KC,81,1159613,14316,80,16222,161,15263
22,23,Detroit Tigers,DET,81,1102623,13612,79,16359,160,14968
23,24,Arizona Diamondbacks,ARI,81,1043010,12876,80,20081,161,16456
24,25,Pittsburgh Pirates,PIT,81,859498,10611,80,20719,161,15633
25,26,Baltimore Orioles,BAL,78,793229,10169,80,16390,158,13319
26,27,Toronto Blue Jays,TOR,80,809557,10119,78,16398,158,13219
27,28,Tampa Bay Rays,TB,80,761072,9513,81,16339,161,12947
28,29,Oakland Athletics,OAK,80,701430,8767,81,19085,161,13958
29,30,Miami Marlins,MIA,81,642617,7933,79,18015,160,12911

In [13]:
# NEW
#
#
#
#

url = 'https://www.spotrac.com/mlb/payroll/2021/'

In [15]:
tables = pd.read_html(url)
tables[0]

,Rank,Team,Win%,Roster,26-Man Payroll,Injured Reserve,Retained,Buried,Suspended,2021 Total Payroll
0,1,Los Angeles Dodgers LAD,0.654,28.0,"$174,661,542","$38,501,103","$6,150,521","$24,070,000",NaN,"$266,020,809"
1,2,New York Yankees NYY,0.568,30.0,"$141,518,753","$48,217,362","$12,129,712","$13,040,875",NaN,"$205,669,863"
2,3,New York Mets NYM,0.475,28.0,"$154,565,754","$33,933,570","$9,524,946","$12,006,000",NaN,"$201,189,189"
3,4,Philadelphia Phillies PHI,0.506,28.0,"$157,714,046","$19,936,225","$13,803,916","$10,533,500",NaN,"$197,213,223"
4,5,Houston Astros HOU,0.586,28.0,"$147,127,725","$39,870,546","$4,134,205","$7,547,600",NaN,"$194,472,041"
5,6,Boston Red Sox BOS,0.568,28.0,"$141,452,731","$2,832,729","$41,374,493","$10,227,500",NaN,"$187,100,784"
6,7,Los Angeles Angels LAA,0.475,28.0,"$30,467,086","$100,777,679","$46,663,119","$8,254,500",NaN,"$180,349,558"
7,8,San Diego Padres SD,0.488,28.0,"$125,977,584","$49,745,500","$2,546,516","$6,926,300",NaN,"$179,764,272"
8,9,San Francisco Giants SF,0.660,28.0,"$134,386,796","$19,766,740","$12,958,219","$16,549,200",NaN,"$171,890,308"
9,10,St. Louis Cardinals STL,0.556,28.0,"$136,018,560","$14,512,682","$19,759,129","$5,171,100",NaN,"$171,469,994"
10,11,Atlanta Braves ATL,0.547,31.0,"$115,664,387","$3,301,950","$17,732,404","$8,925,000",NaN,"$153,060,458"
11,12,Toronto Blue Jays TOR,0.562,28.0,"$108,402,749","$8,853,529","$28,315,121","$9,968,100",NaN,"$150,140,253"
12,13,Chicago Cubs CHC,0.438,28.0,"$33,910,889","$38,534,396","$71,494,409","$1,717,500",NaN,"$144,607,670"
13,14,Washington Nationals WSH,0.401,28.0,"$50,076,145","$34,877,122","$57,061,332","$6,925,200",NaN,"$144,415,187"
14,15,Chicago White Sox CHW,0.574,28.0,"$125,829,369","$3,193,240","$10,099,143","$5,997,000",NaN,"$140,926,169"
15,League Average,League Average,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,League Average,League Average,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"$132,189,858"
17,16,Cincinnati Reds CIN,0.512,28.0,"$84,625,436","$35,531,500","$4,226,409","$5,156,000",NaN,"$125,887,446"
18,17,Minnesota Twins MIN,0.451,28.0,"$83,609,495","$13,198,044","$19,934,219","$9,234,500",NaN,"$120,084,606"
19,18,Colorado Rockies COL,0.460,28.0,"$79,895,422","$5,931,272","$19,571,956","$7,398,500",NaN,"$116,408,966"
20,19,Milwaukee Brewers MIL,0.586,28.0,"$79,937,621","$3,109,474","$10,266,654","$12,221,766",NaN,"$99,377,415"
21,20,Texas Rangers TEX,0.370,28.0,"$24,843,032","$7,899,375","$58,916,700","$9,453,000",NaN,"$95,788,819"
22,21,Kansas City Royals KC,0.457,28.0,"$52,514,932","$15,758,956","$21,740,784","$5,147,900",NaN,"$91,595,545"
23,22,Arizona Diamondbacks ARI,0.321,28.0,"$52,829,878","$9,694,478","$25,868,212","$8,056,000",NaN,"$91,232,929"
24,23,Oakland Athletics OAK,0.531,28.0,"$51,210,210","$34,397,095","$2,500,111","$4,158,000","$580,500","$90,400,598"
25,24,Detroit Tigers DET,0.475,28.0,"$61,408,153","$13,503,703","$8,352,752","$4,374,100",NaN,"$86,348,945"
26,25,Seattle Mariners SEA,0.556,28.0,"$57,025,609","$16,037,933","$8,004,079","$8,276,000","$570,500","$83,837,448"
27,26,Tampa Bay Rays TB,0.617,28.0,"$44,288,651","$18,352,159","$6,218,025","$7,136,100",NaN,"$70,836,327"
28,27,Miami Marlins MIA,0.414,28.0,"$16,304,223","$15,489,077","$23,940,904","$9,320,500",NaN,"$58,157,900"
29,28,Pittsburgh Pirates PIT,0.377,28.0,"$16,572,841","$7,847,255","$19,989,602","$7,368,500","$7,750,000","$54,356,609"
30,29,Cleveland Indians CLE,0.494,28.0,"$35,682,311","$1,367,760","$11,873,544","$5,174,000",NaN,"$50,670,534"
31,30,Baltimore Orioles BAL,0.321,28.0,"$13,838,690","$7,682,535","$30,378,953","$5,737,200",NaN,"$42,421,870"